export const GET_OPENDATA_INITIAL = 'GET_OPENDATA_INITIAL';
export const GET_OPENDATA_SUCCESS = 'GET_OPENDATA_SUCCESS';
export const GET_OPENDATA_FAIL = 'GET_OPENDATA_FAIL';
export const SEARCH_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE';
export const SEARCH_INPUT_ENTER = 'SEARCH_INPUT_ENTER';
export const FILTER_DATA_INITIAL = 'FILTER_DATA_INITIAL';
export const FILTER_DATA_SUCCESS = 'FILTER_DATA_SUCCESS';
